import { Command } from 'commander';
import * as path from 'path';
import { DirectoryManager } from '../lib/directoryManager';
import { AgentFileGenerator, PlaceholderValues } from '../lib/agentFileGenerator';
import { ProjectDetector } from '../lib/projectDetector';
import { InteractiveSetup } from '../lib/interactiveSetup';
import { logger } from '../lib/logger';

export const initCommand = new Command('init')
  .description('Initialize Memento Protocol in the current project')
  .option('-f, --force', 'Force initialization even if .memento already exists')
  .option('-q, --quick', 'Quick setup with recommended components')
  .option('-i, --interactive', 'Interactive setup mode (default)')
  .option('-g, --gitignore', 'Add .memento/ to .gitignore (defaults to false)')
  .action(async (options) => {
    try {
      const projectRoot = process.cwd();
      const dirManager = new DirectoryManager(projectRoot);
      const projectDetector = new ProjectDetector(projectRoot);
      
      // Check if already initialized
      if (dirManager.isInitialized() && !options.force) {
        logger.warn('Memento Protocol is already initialized in this project.');
        logger.info('Use --force to reinitialize.');
        return;
      }

      // Initialize directory structure
      logger.info('Initializing Memento Protocol...');
      await dirManager.initializeStructure();
      
      // Detect project type
      logger.info('Detecting project type...');
      const projectInfo = await projectDetector.detect();
      logger.info(`Project type: ${projectInfo.type}${projectInfo.framework ? ` (${projectInfo.framework})` : ''}`);
      
      // Run setup flow
      const interactiveSetup = new InteractiveSetup(projectRoot);
      let setupOptions;
      
      if (options.quick) {
        // Quick setup with recommended components
        setupOptions = await interactiveSetup.quickSetup(projectInfo);
      } else if (options.interactive !== false) {
        // Interactive setup (default)
        setupOptions = await interactiveSetup.run(projectInfo);
      } else {
        // Basic setup without component installation
        setupOptions = {
          projectInfo,
          selectedModes: [],
          selectedWorkflows: [],
          selectedAgents: ['claude'], // Default to Claude for basic setup
          addToGitignore: false
        };
      }
      
      // Update .gitignore if requested via CLI flag or interactive setup
      if (options.gitignore || setupOptions.addToGitignore) {
        await dirManager.ensureGitignore();
      }
      
      // Apply setup (install components and save config)
      if (setupOptions.selectedModes.length > 0 || 
          setupOptions.selectedWorkflows.length > 0) {
        logger.space();
        logger.info('Installing selected components...');
        await interactiveSetup.applySetup({
          ...setupOptions,
          force: options.force
        });
      }
      
      // Generate agent files for all selected agents
      logger.space();
      logger.info('Generating agent instruction files...');
      
      // Load agent metadata
      const agentMetadata = await AgentFileGenerator.loadAgentMetadata(projectRoot);
      const agentGenerator = new AgentFileGenerator(projectRoot);
      
      // Prepare placeholder values
      const placeholderValues: PlaceholderValues = {
        PROJECT_NAME: path.basename(projectRoot),
        PROJECT_DESCRIPTION: `${projectInfo.type} project${projectInfo.framework ? ` using ${projectInfo.framework}` : ''}`,
        DEFAULT_MODE: setupOptions.defaultMode,
        // Add more placeholder values as needed
      };
      
      // Generate files for each selected agent
      for (const agentId of setupOptions.selectedAgents) {
        const agentConfig = agentMetadata[agentId];
        if (!agentConfig) {
          logger.warn(`No template found for agent: ${agentId}`);
          continue;
        }
        
        // Check for existing content
        const existingContent = await agentGenerator.readExisting(agentConfig.targetFilename);
        
        // Generate the file
        await agentGenerator.generate(agentConfig, placeholderValues, existingContent || undefined);
      }
      
      // Note: CLAUDE.md is now generated by AgentFileGenerator
      
      logger.space();
      logger.success('Memento Protocol initialized successfully!');
      logger.space();
      
      // Show agent-specific instructions
      if (setupOptions.selectedAgents.includes('claude')) {
        logger.info('To use with Claude Code:');
        logger.info('  - Say "act as [mode]" to switch behavioral patterns');
        logger.info('  - Say "execute [workflow]" to run procedures');
        logger.info('  - Say "create ticket [name]" to start persistent work');
        logger.space();
      }
      
      if (setupOptions.selectedAgents.includes('cursor')) {
        logger.info('To use with Cursor:');
        logger.info('  - .cursorrules file has been generated with project conventions');
        logger.info('  - The AI will automatically follow these coding guidelines');
        logger.space();
      }
      
      if (setupOptions.selectedAgents.includes('gemini')) {
        logger.info('To use with Gemini:');
        logger.info('  - GEMINI.md file has been generated with project context');
        logger.info('  - Reference this file when working with Google\'s AI tools');
        logger.space();
      }
      
      logger.info('Run "memento --help" to see all available commands.');
    } catch (error) {
      logger.error('Failed to initialize Memento Protocol:', error);
      process.exit(1);
    }
  });