[[hooks]]
event = "UserPromptSubmit"
command = "./.memento/hooks/routing.sh"

# Memento Protocol Hooks

[[hooks]]
event = "UserPromptSubmit"
command = "echo 'BLOCKED: Super-user commands are not allowed for safety.' >&2 && exit 2"

[[hooks]]
event = "UserPromptSubmit"
command = "/Users/dazheng/workspace/personal/memento-protocol/.memento/hooks/scripts/acronym-expander-1753975308575.sh"

[[hooks]]
event = "SessionStart"
command = "echo '## Project Context' && echo && echo '### Git Status' && git status -s 2>/dev/null || echo 'Not a git repository' && echo && echo '### Recent Commits' && git log --oneline -5 2>/dev/null || true && echo && echo '### Project Structure' && find . -type f -name '*.json' -o -name '*.js' -o -name '*.ts' -o -name '*.py' -o -name '*.java' -o -name '*.go' | grep -E -v '(node_modules|.git|dist|build|target)' | head -20 || true"
