name: Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run all tests
      run: npm test
    
    - name: Run mode heading conformity test
      run: npm test -- src/lib/__tests__/modeHeadingConformity.test.ts
  
  validate-mode-files:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Check mode template files for required sections
      run: |
        set -e
        echo "Checking mode template files for all required sections..."
        
        TEMPLATE_MODE_FILES="templates/modes/*.md"
        REQUIRED_SECTIONS=(
          "Behavioral Guidelines"
          "Core Responsibilities" 
          "Best Practices"
          "Mode Switching Triggers"
          "Done When"
          "Example Commands"
        )
        ERRORS=0
        
        for file in $TEMPLATE_MODE_FILES; do
          if [ -f "$file" ] && [[ "$file" != *"metadata.json" ]]; then
            echo ""
            echo "Checking $file..."
            
            # Check for required sections
            for section in "${REQUIRED_SECTIONS[@]}"; do
              if ! grep -q "^## $section" "$file"; then
                echo "  ❌ Missing required section: ## $section"
                ERRORS=$((ERRORS + 1))
              else
                echo "  ✓ Contains section: ## $section"
              fi
            done
            
            # Check section order
            echo "  Checking section order..."
            FOUND_INDICES=""
            LINE_NUM=0
            while IFS= read -r line; do
              LINE_NUM=$((LINE_NUM + 1))
              for i in "${!REQUIRED_SECTIONS[@]}"; do
                if [[ "$line" == "## ${REQUIRED_SECTIONS[$i]}" ]]; then
                  FOUND_INDICES="$FOUND_INDICES $i:$LINE_NUM"
                fi
              done
            done < "$file"
            
            # Verify order
            PREV_LINE=0
            ORDER_CORRECT=true
            for entry in $FOUND_INDICES; do
              INDEX="${entry%%:*}"
              LINE="${entry##*:}"
              if [ $LINE -lt $PREV_LINE ]; then
                ORDER_CORRECT=false
                break
              fi
              PREV_LINE=$LINE
            done
            
            if [ "$ORDER_CORRECT" = true ]; then
              echo "  ✓ Sections are in correct order"
            else
              echo "  ❌ Sections are not in the required order"
              ERRORS=$((ERRORS + 1))
            fi
            
            # Check for Behavioral Guidelines subsections
            if grep -q "^## Behavioral Guidelines" "$file"; then
              BG_START=$(grep -n "^## Behavioral Guidelines" "$file" | cut -d: -f1)
              BG_END=$(grep -n "^## Core Responsibilities" "$file" | cut -d: -f1)
              
              if [ -n "$BG_START" ] && [ -n "$BG_END" ]; then
                SECTION_CONTENT=$(sed -n "${BG_START},${BG_END}p" "$file")
                
                if echo "$SECTION_CONTENT" | grep -q "^### Communication Style"; then
                  echo "  ✓ Contains ### Communication Style"
                else
                  echo "  ❌ Missing ### Communication Style under Behavioral Guidelines"
                  ERRORS=$((ERRORS + 1))
                fi
                
                if echo "$SECTION_CONTENT" | grep -q "^### Decision Making"; then
                  echo "  ✓ Contains ### Decision Making"
                else
                  echo "  ❌ Missing ### Decision Making under Behavioral Guidelines"
                  ERRORS=$((ERRORS + 1))
                fi
              fi
            fi
          fi
        done
        
        echo ""
        if [ $ERRORS -gt 0 ]; then
          echo "FAILED: Found $ERRORS error(s) in mode template files"
          exit 1
        else
          echo "SUCCESS: All mode template files have valid structure"
        fi
    
    - name: Check project mode files contain "Done When" section
      run: |
        set -e
        echo "Checking project mode files for 'Done When' section..."
        
        MODE_FILES=".memento/modes/*.md"
        MISSING_SECTIONS=0
        
        for file in $MODE_FILES; do
          if [ -f "$file" ]; then
            if ! grep -q "^## Done When" "$file"; then
              echo "ERROR: $file is missing '## Done When' section"
              MISSING_SECTIONS=$((MISSING_SECTIONS + 1))
            else
              echo "✓ $file contains 'Done When' section"
            fi
          fi
        done
        
        if [ $MISSING_SECTIONS -gt 0 ]; then
          echo ""
          echo "FAILED: $MISSING_SECTIONS mode file(s) missing 'Done When' section"
          exit 1
        else
          echo ""
          echo "SUCCESS: All project mode files contain 'Done When' section"
        fi